"""Consolidated machine-readable reference data for cohort curation."""

from __future__ import annotations

from pathlib import Path
from typing import Any

DATA_ROOT_ENV_VAR = 'COHORT_CURATION_DATA_ROOT'

# When no explicit root is provided, these locations are checked in order.
DEFAULT_DATA_ROOT_CANDIDATES = (
    Path("data"),
    Path("data/msk_solid_heme_epic"),
)

FILE_NAMES = {'patient': 'data_clinical_patient.txt',
 'sample': 'data_clinical_sample.txt',
 'ancestry': 'data_clinical_supp_ancestry.txt',
 'mutations': 'data_mutations_extended.txt',
 'sv': 'data_sv.txt',
 'cna_long': 'data_CNA_long_format.txt',
 'diagnosis': 'data_timeline_diagnosis.txt',
 'follow_up': 'data_timeline_follow_up.txt',
 'specimen_surgery': 'data_timeline_specimen_surgery.txt',
 'tumor_sites': 'data_timeline_tumor_sites.txt',
 'cancer_presence': 'data_timeline_cancer_presence.txt',
 'progression': 'data_timeline_progression.txt',
 'treatment': 'data_timeline_treatment.txt',
 'surgery': 'data_timeline_surgery.txt',
 'radiation': 'data_timeline_radiation.txt',
 'mmr': 'data_timeline_mmr.txt',
 'pdl1': 'data_timeline_pdl1.txt',
 'gleason': 'data_timeline_gleason.txt',
 'labs_metabolic_tsv': 'labs_metabolic_20240813.tsv',
 'ca_15_3_labs': 'data_timeline_ca_15_3_labs.txt',
 'ca_19_9_labs': 'data_timeline_ca_19_9_labs.txt',
 'ca_125_labs': 'data_timeline_ca_125_labs.txt',
 'cea_labs': 'data_timeline_cea_labs.txt',
 'psa_labs': 'data_timeline_psa_labs.txt',
 'tsh_labs': 'data_timeline_tsh_labs.txt',
 'bmi': 'data_timeline_bmi.txt',
 'ecog_kps': 'data_timeline_ecog_kps.txt'}

PATIENT_PRIOR_MED_MAP = {'Prior medications to MSK': 'Yes', 'No prior medications': 'No', 'Unknown': 'Unknown'}

PATIENT_SMOKING_MAP = {'Former/Current Smoker': 'Yes', 'Never': 'Never', 'Unknown': 'Unknown'}

PATIENT_OS_STATUS_MAP = {'1:DECEASED': 'Deceased', '0:LIVING': 'Living'}

ACTION_LABELS = {'sample': 'SEQUENCE',
 'diagnosis': 'DIAGNOSE',
 'labs': 'LAB',
 'tumor_sites': 'OBSERVE',
 'progression': 'PROGRESSION',
 'treatment': 'TREAT',
 'histopath': 'HISTOPATH',
 'followup_first_consult': 'FIRST_CONSULT'}

RECOGNIZED_CONSTANTS = {'treatment_names': ['4-Hydroperoxy-Cyclophosphamide',
                     'Abarelix',
                     'Abemaciclib',
                     'Abiraterone',
                     'Ac225 H11B6 Med 20-321',
                     'Ac225-Fpi-1434',
                     'Ac225-Fpi-1966',
                     'Acalabrutinib',
                     'Adagrasib',
                     'Ado-Trastuzumab Emtansine',
                     'Afatinib',
                     'Aflibercept Ophthalmic',
                     'Aldesleukin',
                     'Alectinib',
                     'Alemtuzumab',
                     'Alpelisib',
                     'Altretamine',
                     'Amivantamab',
                     'Anastrozole',
                     'Apalutamide',
                     'Arsenic Trioxide',
                     'Asciminib',
                     'Asparaginase Erwinia Chrysanthemi',
                     'Asparaginase Escherichia Coli',
                     'Atezolizumab',
                     'Avapritinib',
                     'Avelumab',
                     'Axicabtagene Ciloleucel',
                     'Axitinib',
                     'Azacitidine',
                     'Bcg',
                     'Belantamab Mafodotin',
                     'Belinostat',
                     'Belzutifan',
                     'Bendamustine',
                     'Bevacizumab',
                     'Bexarotene',
                     'Bexarotene Topical',
                     'Bicalutamide',
                     'Binimetinib',
                     'Bleomycin',
                     'Blinatumomab',
                     'Bortezomib',
                     'Bosutinib',
                     'Brentuximab Vedotin',
                     'Brexucabtagene Autoleucel',
                     'Brigatinib',
                     'Busulfan',
                     'Cabazitaxel',
                     'Cabozantinib',
                     'Calaspargase Pegol',
                     'Capecitabine',
                     'Capivasertib',
                     'Capmatinib',
                     'Carboplatin',
                     'Carfilzomib',
                     'Carmustine',
                     'Cedazuridine-Decitabine',
                     'Cemiplimab',
                     'Ceritinib',
                     'Cetuximab',
                     'Chlorambucil',
                     'Ciltacabtagene Autoleucel',
                     'Cisplatin',
                     'Cladribine',
                     'Clofarabine',
                     'Cobimetinib',
                     'Copanlisib',
                     'Crizotinib',
                     "Cu64 Nota-Psmai-Peg-Cy55-C' Dots",
                     'Cyclophosphamide',
                     'Cytarabine',
                     'Cytarabine Liposomal',
                     'Cytarabine Liposomal-Daunorubicin Liposomal',
                     'Dabrafenib',
                     'Dacarbazine',
                     'Dacomitinib',
                     'Dactinomycin',
                     'Daratumumab',
                     'Daratumumab-Hyaluronidase',
                     'Darolutamide',
                     'Dasatinib',
                     'Daunorubicin',
                     'Decitabine',
                     'Degarelix',
                     'Denileukin Diftitox',
                     'Deucravacitinib',
                     'Diethylstilbestrol',
                     'Dinutuximab',
                     'Docetaxel',
                     'Dostarlimab',
                     'Doxorubicin',
                     'Doxorubicin Liposomal',
                     'Durvalumab',
                     'Duvelisib',
                     'Eculizumab',
                     'Eflornithine',
                     'Elacestrant',
                     'Elotuzumab',
                     'Elranatamab',
                     'Emapalumab',
                     'Enasidenib',
                     'Encorafenib',
                     'Enfortumab Vedotin',
                     'Entrectinib',
                     'Enzalutamide',
                     'Epcoritamab',
                     'Epirubicin',
                     'Erdafitinib',
                     'Eribulin',
                     'Erlotinib',
                     'Estramustine',
                     'Etoposide',
                     'Etoposide Phosphate',
                     'Everolimus',
                     'Exemestane',
                     'Fam-Trastuzumab Deruxtecan',
                     'Fedratinib',
                     'Floxuridine',
                     'Fludarabine',
                     'Fluorouracil',
                     'Fluorouracil Topical',
                     'Fluoxymesterone',
                     'Flutamide',
                     'Fruquintinib',
                     'Fulvestrant',
                     'Futibatinib',
                     'Gefitinib',
                     'Gemcitabine',
                     'Gemtuzumab Ozogamicin',
                     'Gilteritinib',
                     'Glasdegib',
                     'Glofitamab',
                     'Goserelin',
                     'Gp100',
                     'Histrelin',
                     'Hyaluronidase-Rituximab',
                     'Hyaluronidase-Trastuzumab',
                     'Hyaluronidase/Pertuzumab/Trastuzumab',
                     'Hydroxyurea',
                     'Ibrutinib',
                     'Idarubicin',
                     'Idecabtagene Vicleucel',
                     'Idelalisib',
                     'Ifosfamide',
                     'Imatinib',
                     'Imetelstat',
                     'Imlunestrant Tosylate',
                     'Inavolisib (Gdc-0077)',
                     'Infigratinib',
                     'Inotuzumab Ozogamicin',
                     'Interferon Alfa-2B',
                     'Investigational',
                     'Ipilimumab',
                     'Irinotecan',
                     'Irinotecan Liposomal',
                     'Isatuximab',
                     'Isotretinoin',
                     'Ivosidenib',
                     'Ixabepilone',
                     'Ixazomib',
                     'Lapatinib',
                     'Larotrectinib',
                     'Lazertinib',
                     'Lenalidomide',
                     'Lenvatinib',
                     'Letrozole',
                     'Letrozole-Ribociclib',
                     'Leucovorin',
                     'Leuprolide',
                     'Levamisole',
                     'Lifileucel',
                     'Lisocabtagene Maraleucel',
                     'Lomustine',
                     'Loncastuximab Tesirine',
                     'Lorlatinib',
                     'Lurbinectedin',
                     'Lutetium Lu-177 5B1-Mvt1075',
                     'Lutetium Lu-177 Dota-Girentiximab',
                     'Lutetium Lu-177 Dota-Jr11',
                     'Lutetium Lu-177 Dotaebtate',
                     'Lutetium Lu-177 Dotatate',
                     'Lutetium Lu-177 Edotreotide',
                     'Lutetium Lu-177 Pnt6555',
                     'Lutetium Lu-177 Psma',
                     'Lutetium Lu-177 Vipivotide Tetraxetan',
                     'Mechlorethamine',
                     'Mechlorethamine Topical',
                     'Megestrol',
                     'Melphalan',
                     'Mercaptopurine',
                     'Methotrexate',
                     'Midostaurin',
                     'Mirvetuximab Soravtansine',
                     'Mitomycin',
                     'Mitomycin Ophthalmic',
                     'Mitotane',
                     'Mitoxantrone',
                     'Mobocertinib',
                     'Mogamulizumab',
                     'Momelotinib',
                     'Mosunetuzumab',
                     'Nadofaragene Firadenovec',
                     'Naxitamab',
                     'Necitumumab',
                     'Nelarabine',
                     'Neratinib',
                     'Nilotinib',
                     'Nilutamide',
                     'Nintedanib',
                     'Niraparib',
                     'Niraparib/Abiraterone',
                     'Nirogacestat',
                     'Nivolumab',
                     'Nivolumab-Relatlimab',
                     'Obecabtagene Autoleucel',
                     'Obinutuzumab',
                     'Ofatumumab',
                     'Olaparib',
                     'Olaratumab',
                     'Olutasidenib',
                     'Omacetaxine',
                     'Osimertinib',
                     'Oxaliplatin',
                     'Paclitaxel',
                     'Paclitaxel Protein-Bound',
                     'Pacritinib',
                     'Palbociclib',
                     'Pamidronate',
                     'Panitumumab',
                     'Panobinostat',
                     'Pazopanib',
                     'Pegaspargase',
                     'Pembrolizumab',
                     'Pemetrexed',
                     'Pemigatinib',
                     'Pentostatin',
                     'Pertuzumab',
                     'Pexidartinib',
                     'Pirtobrutinib',
                     'Polatuzumab Vedotin',
                     'Pomalidomide',
                     'Ponatinib',
                     'Pralatrexate',
                     'Pralsetinib',
                     'Procarbazine',
                     'Quizartinib',
                     'Radium Ra-223 Chloride',
                     'Radium Ra-223 Dichloride',
                     'Raloxifene',
                     'Ramucirumab',
                     'Ravulizumab',
                     'Regorafenib',
                     'Relugolix',
                     'Repotrectinib',
                     'Retifanlimab',
                     'Revumenib (Sndx-5613)',
                     'Ribociclib',
                     'Ripretinib',
                     'Ritlecitinib',
                     'Rituximab',
                     'Rociletinib',
                     'Romidepsin',
                     'Rucaparib',
                     'Ruxolitinib',
                     'Sacituzumab Govitecan',
                     'Samarium Sm-153 Lexidronam',
                     'Selinexor',
                     'Selpercatinib',
                     'Selumetinib',
                     'Siltuximab',
                     'Sipuleucel-T',
                     'Sirolimus Protein-Bound',
                     'Sirolimus Topical',
                     'Sodium Iodide I-131',
                     'Sodium Iodide I-131 3F8',
                     'Sodium Iodide I-131 8H9',
                     'Sodium Iodide I-131 Anti-B1',
                     'Sodium Iodide I-131 Bc8 Anticd45',
                     'Sodium Iodide I-131 Clr1404',
                     'Sodium Iodide I-131 Mibg',
                     'Sodium Iodide I-131 Mip-1095',
                     'Sodium Iodide I-131 Omburtamab 8H9',
                     'Sodium Iodide I-131 Tositumomab',
                     'Sodium Iodidei-131 Apamistamab',
                     'Sonidegib',
                     'Sorafenib',
                     'Sotorasib',
                     'Streptozocin',
                     'Sunitinib',
                     'Tafasitamab',
                     'Tagraxofusp',
                     'Talazoparib',
                     'Talimogene Laherparepvec',
                     'Talquetamab',
                     'Tamoxifen',
                     'Tarlatamab',
                     'Tazemetostat',
                     'Tebentafusp',
                     'Teclistamab',
                     'Temozolomide',
                     'Temsirolimus',
                     'Tepotinib',
                     'Thalidomide',
                     'Thioguanine',
                     'Thiotepa',
                     'Tipiracil-Trifluridine',
                     'Tisagenlecleucel',
                     'Tisotumab Vedotin',
                     'Tivozanib',
                     'Topotecan',
                     'Toremifene',
                     'Toripalimab',
                     'Tovorafenib',
                     'Trabectedin',
                     'Trametinib',
                     'Trastuzumab',
                     'Tremelimumab',
                     'Tretinoin',
                     'Trilaciclib',
                     'Triptorelin',
                     'Tucatinib',
                     'Umbralisib',
                     'Unknown',
                     'Valrubicin',
                     'Vandetanib',
                     'Veliparib (Abt-888)',
                     'Vemurafenib',
                     'Venetoclax',
                     'Vimseltinib (Dcc-3014)',
                     'Vinblastine',
                     'Vincristine',
                     'Vincristine Liposome',
                     'Vinorelbine',
                     'Vismodegib',
                     'Vorasidenib',
                     'Vorinostat',
                     'Yttrium Y-90 Clivatuzumab',
                     'Yttrium Y-90 Ibritumomab Tiuxetan',
                     'Yttrium Y-90 Microspheres',
                     'Yttrium Y-90 Theraspheres',
                     'Zanidatamab (Zw25)',
                     'Zanubrutinib',
                     'Zolbetuximab (Imab362)',
                     'Zoledronic Acid',
                     'Zongertinib'],
 'genomic_panel_names': ['ACCESS-HEME-115',
                         'ACCESS129',
                         'ACCESS146',
                         'IMPACT-HEME-400',
                         'IMPACT-HEME-468',
                         'IMPACT341',
                         'IMPACT410',
                         'IMPACT468',
                         'IMPACT505'],
 'ancestry_labels': ['ADM', 'AFR', 'ASJ', 'EAS', 'EUR', 'NAM', 'SAS'],
 'sex_labels': ['Female', 'Male', 'Unknown'],
 'ethnicity_labels': ['Non-Spanish; Non-Hispanic', 'Other', 'Spanish  NOS; Hispanic NOS, Latino NOS', 'Unknown'],
 'smoking_labels': ['Never', 'Unknown', 'Yes'],
 'prior_medication_labels': ['No', 'Unknown', 'Yes'],
 'os_status_labels': ['Deceased', 'Living'],
 'sample_type_labels': ['Local-Recurrence', 'Metastasis', 'Primary', 'Unknown'],
 'msi_type_labels': ['Indeterminate', 'Instable', 'Not-evaluable', 'Stable', 'Unknown'],
 'action_labels': ['DIAGNOSE', 'FIRST_CONSULT', 'HISTOPATH', 'LAB', 'OBSERVE', 'PROGRESSION', 'SEQUENCE', 'TREAT']}

DATAFRAME_INTERFACES = {'patient.load_patient_harmonized': {'required_keys': ['PATIENT_ID'],
                                     'harmonized_fields': ['PRIOR_MED_TO_MSK',
                                                           'SMOKING_PRED',
                                                           'OS_STATUS',
                                                           'OS_DAYS',
                                                           'ANCESTRY_LABEL'],
                                     'notes': 'Preserves most source columns; drops OS_MONTHS after deriving OS_DAYS.'},
 'diagnosis.load_diagnosis_harmonized': {'core_keys': ['PATIENT_ID', 'START_DATE', 'ACTION'],
                                         'stage_fields': ['CLINICAL_GROUP', 'STAGE_CDM_DERIVED_GRANULAR', 'STAGE'],
                                         'disease_fields': ['CANCER_TYPE',
                                                            'CANCER_TYPE_DETAILED',
                                                            'CANCER_SITE',
                                                            'CANCER_SITE_DETAILED',
                                                            'MORPH_CODE',
                                                            'TOPOLOGY_CODE'],
                                         'notes': 'Output is restricted to known diagnosis columns present in source.'},
 'genomics.load_sample_harmonized': {'core_keys': ['SAMPLE_ID', 'PATIENT_ID', 'START_DATE', 'ACTION'],
                                     'disease_sample_fields': ['CANCER_TYPE',
                                                               'CANCER_TYPE_DETAILED',
                                                               'ONCOTREE_CODE',
                                                               'SAMPLE_TYPE',
                                                               'PRIMARY_SITE',
                                                               'METASTATIC_SITE'],
                                     'assay_fields': ['MSI_TYPE',
                                                      'TUMOR_PURITY',
                                                      'CVR_TMB_COHORT_DECILE',
                                                      'WEEK_ADDED'],
                                     'notes': 'CVR_TMB_COHORT_PERCENTILE is converted to CVR_TMB_COHORT_DECILE when '
                                              'present.'},
 'genomics.load_mutations_raw': {'core_keys': ['SAMPLE_ID'],
                                 'filter_fields': ['Hugo_Symbol', 'Variant_Classification'],
                                 'notes': 'Renames Tumor_Sample_Barcode to SAMPLE_ID when present.'},
 'genomics.load_cna_raw': {'core_keys': ['SAMPLE_ID', 'Hugo_Symbol'],
                           'fields': ['Alteration', 'ALTERATION_LABEL'],
                           'notes': 'ALTERATION_LABEL is derived from numeric alteration values.'},
 'genomics.load_sv_raw': {'core_keys': ['SAMPLE_ID'],
                          'gene_fields': ['Site1_Hugo_Symbol', 'Site2_Hugo_Symbol'],
                          'notes': 'One row per structural-variant event in source table.'},
 'genomics.load_genomics_event_table': {'core_keys': ['SAMPLE_ID', 'PATIENT_ID'],
                                        'genomic_event_fields': ['GENE_ALT',
                                                                 'MUTATION_COUNT',
                                                                 'SV_EVENT_COUNT',
                                                                 'Alteration',
                                                                 'ALTERATION_LABEL'],
                                        'timeline_fields': ['START_DATE', 'ACTION'],
                                        'notes': 'Outer merge of mutation, CNA, and SV events by sample and gene.'},
 'procedures.load_treatment_harmonized': {'core_keys': ['PATIENT_ID', 'START_DATE', 'STOP_DATE', 'ACTION'],
                                          'treatment_fields': ['TREATMENT', 'AGENT'],
                                          'notes': 'Missing STOP_DATE values are filled from START_DATE + 1.'},
 'procedures.load_surgery_harmonized': {'core_keys': ['PATIENT_ID', 'START_DATE', 'STOP_DATE', 'ACTION'],
                                        'surgery_fields': ['PROCEDURE_DESCRIPTION', 'SURGERY_CATEGORY', 'AGENT'],
                                        'notes': 'SURGERY_CATEGORY is mapped with surg_purpose_map.csv DATA -> '
                                                 'REFINEMENT_RESULT.'},
 'procedures.load_curative_surgery_harmonized': {'core_keys': ['PATIENT_ID', 'START_DATE', 'STOP_DATE', 'ACTION'],
                                                 'surgery_fields': ['PROCEDURE_DESCRIPTION',
                                                                    'SURGERY_CATEGORY',
                                                                    'AGENT'],
                                                 'notes': 'Returns only rows where SURGERY_CATEGORY == Tumor removal.'},
 'procedures.load_radiation_harmonized': {'core_keys': ['PATIENT_ID', 'START_DATE', 'STOP_DATE', 'ACTION'],
                                          'radiation_fields': ['PLAN', 'RADIATION_CATEGORY', 'AGENT'],
                                          'notes': 'RADIATION_CATEGORY is populated when mapping file is available.'},
 'imaging.load_tumor_sites_harmonized': {'core_keys': ['PATIENT_ID', 'START_DATE', 'ACTION'],
                                         'site_fields': ['SOURCE_SPECIFIC', 'TUMOR_SITE'],
                                         'notes': 'Duplicate rows are dropped.'},
 'imaging.load_progression_harmonized': {'core_keys': ['PATIENT_ID', 'START_DATE', 'ACTION'],
                                         'progression_fields': ['PROGRESSION',
                                                                'PROGRESSION_PROBABILITY',
                                                                'PROGRESSION_LABEL',
                                                                'SOURCE_SPECIFIC'],
                                         'notes': 'PROGRESSION_LABEL is derived from Yes/No progression values.'},
 'histopathology.load_histopathology_harmonized': {'core_keys': ['PATIENT_ID', 'START_DATE', 'ACTION'],
                                                   'marker_fields': 'MMR, PDL1, and Gleason component columns when '
                                                                    'present.',
                                                   'notes': 'Outer merge across component tables keyed on PATIENT_ID '
                                                            'and START_DATE.'},
 'followup.load_followup_first_consult': {'core_keys': ['PATIENT_ID', 'START_DATE', 'ACTION'],
                                          'fields': 'Additional source columns after dropping EVENT_TYPE, SUBTYPE, '
                                                    'SOURCE.',
                                          'notes': 'Records restricted to SOURCE == First Consult.'},
 'labs.load_labs_harmonized': {'core_keys': ['PATIENT_ID', 'START_DATE', 'ACTION'],
                               'lab_value_fields': ['LR_SUBTEST_NAME', 'LR_RESULT_VALUE'],
                               'notes': 'Combines metabolic and supplementary labs; applies lab-name normalization.'}}


def get_recognized_constants(category: str | None = None) -> dict[str, Any] | list[str]:
    """Return all recognized constants or a single category."""
    if category is None:
        return RECOGNIZED_CONSTANTS
    value = RECOGNIZED_CONSTANTS.get(category, [])
    if isinstance(value, list):
        return value
    if isinstance(value, dict):
        return value
    return []


def get_dataframe_interface(loader_name: str) -> dict[str, Any]:
    """Return dataframe interface metadata for a loader."""
    value = DATAFRAME_INTERFACES.get(loader_name, {})
    return value if isinstance(value, dict) else {}
